In [21]:
# A simple SVD Recommender system


#importing neccessary packages
from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split

# Load the movielens-100k dataset (it wil download it if needed)

data=Dataset.load_builtin('ml-100k')
#Dividing the Data in test and train
trainset, testset=train_test_split(data, test_size=.20)

#initializing the SVD algorithm
model=SVD()

# Fitting the model
model.fit(trainset)

#making the prediction
prediction=model.test(testset)

#computing the error(RMSE in this case)
accuracy.rmse(prediction)

#predicting rating for a user for a movie

uid=str(450) # raw user id

lid=str(130)

#get a prediction for specific users and items

pred=model.predict(uid, lid)

# view predicting rating
pred.est 


RMSE: 0.9351


2.996535028031628

In [19]:
# how to use SVD to decompose a matrix using Python.

from scipy.sparse import csc_matrix # we use the csc_matrix to create a sparse matrix object
from scipy.sparse.linalg import svds

import numpy as np


# Create a sparse matrix 
A = csc_matrix([[1, 0, 0], [5, 0, 2], [0, 1, 0], [0, 0, 3], [4, 0, 9]], dtype=float)

# Apply SVD
u, s, vt = svds(A, k=2) # k is the number of stretching factors

print ('A:\n', A.toarray())
print ('=')
print ('\nU:\n', u)
print ('\nΣ:\n', s)
print ('\nV.T:\n', vt)



print('\nApproximation of Ratings Matrix')
u.dot(np.diag(s).dot(vt))


print('\nRounded Approximation of Ratings Matrix')
np.round(u.dot(np.diag(s).dot(vt)))


A:
 [[1. 0. 0.]
 [5. 0. 2.]
 [0. 1. 0.]
 [0. 0. 3.]
 [4. 0. 9.]]
=

U:
 [[ 2.21829477e-01  4.58445949e-02]
 [ 8.50288016e-01  3.86369035e-01]
 [ 1.00495461e-17  9.54838383e-18]
 [-3.88289052e-01  2.35719092e-01]
 [-2.77549248e-01  8.90535654e-01]]

Σ:
 [ 3.89366418 10.99269663]

V.T:
 [[ 8.63729488e-01  3.91295578e-17 -5.03955724e-01]
 [ 5.03955724e-01  1.04962487e-16  8.63729488e-01]]

Approximation of Ratings Matrix

Rounded Approximation of Ratings Matrix


array([[1., 0., 0.],
       [5., 0., 2.],
       [0., 0., 0.],
       [0., 0., 3.],
       [4., 0., 9.]])